<a href="https://colab.research.google.com/github/Far0311/Data-Analysis-with-Phyton/blob/main/Accessing%20and%20Changing%20Elements%2C%20Rows%2C%20Columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
a.shape

(2, 7)

In [5]:
#get specific element [row, column]
a[1,5]

13

In [6]:
a[1,-2]

13

In [7]:
#get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
#get specific column
a[:, 2]

array([ 3, 10])

In [9]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [10]:
a[0, 1:-1:2]

array([2, 4, 6])

In [11]:
#replace a number
a[1,5] = 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [12]:
a[:,2] = 5
print (a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [14]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [16]:
#3-d example
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print (b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
#get specific element (work outside in)
b[0,1,1]

4

In [20]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print (b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [21]:
b[:,1,:]


array([[9, 9],
       [8, 8]])