<a href="https://colab.research.google.com/github/Far0311/Data-Analysis-with-Phyton/blob/main/BasicsofNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [13]:
a = np.array([1 ,2, 3], dtype = 'int16') #specify the size if we know theres no big values
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#Get Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
#get shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [14]:
#get type
a.dtype

dtype('int16')

In [12]:
b.dtype

dtype('float64')

In [15]:
#get size
a.itemsize

2

In [18]:
#get total size
a.size * a.itemsize

6

In [19]:
a.nbytes

6

In [20]:
b.itemsize

8

In [21]:
b.nbytes

48