<a href="https://colab.research.google.com/github/Far0311/Data-Analysis-with-Phyton/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Accessing and Changing Elements, Rows, Columns

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
a.shape

(2, 7)

In [5]:
#get specific element [row, column]
a[1,5]

13

In [6]:
a[1,-2]

13

In [7]:
#get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
#get specific column
a[:, 2]

array([ 3, 10])

In [9]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [10]:
a[0, 1:-1:2]

array([2, 4, 6])

In [11]:
#replace a number
a[1,5] = 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [12]:
a[:,2] = 5
print (a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [14]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [16]:
#3-d example
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print (b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
#get specific element (work outside in)
b[0,1,1]

4

In [20]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print (b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [21]:
b[:,1,:]


array([[9, 9],
       [8, 8]])

# Initializing Different Arrays

In [22]:
#ALL 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
#ALL 1s matrix
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [28]:
#any other number
np.full((2,2), 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [29]:
#any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [31]:
#random decimal numbers
np.random.rand(4,2,3)

array([[[0.88131087, 0.59579822, 0.27699938],
        [0.13331568, 0.54466185, 0.81617392]],

       [[0.09666376, 0.40198851, 0.68739703],
        [0.05660907, 0.79059436, 0.61712063]],

       [[0.83920247, 0.01326169, 0.26683274],
        [0.73882056, 0.7410051 , 0.60948911]],

       [[0.53421499, 0.13177928, 0.08681045],
        [0.83295792, 0.49458181, 0.59190829]]])

In [32]:
np.random.random_sample(a.shape)

array([[0.88276906, 0.37081571, 0.98722754, 0.07538807, 0.82907836,
        0.77551553, 0.30682554],
       [0.63870308, 0.88709042, 0.0422734 , 0.16756281, 0.11396727,
        0.86645456, 0.47455002]])

In [34]:
# Random Integer values
np.random.randint(4,8, size=(3,3))

array([[7, 7, 6],
       [5, 4, 7],
       [6, 5, 7]])

In [35]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr , 3, axis = 0)
print (r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
